exec(open('util.py').read())
def log(inp):
	
	"""
	ope.append("pro")
	ope.append("ins")
	ope.append("go2")
	ope.append("caf")
	ope.append("kee")
	ope.append("gma")
	ope.append("twi")
	ope.append("fac")
	ope.append("rel")	
	"""
	mas = []
	#info mas.append(['','Mikael', 'Sandstedt', '07/30/90', '5403223655', '', ''])
	mas.append(['wor', 'wordpress', 'violin78@protonmail.com', 'Viovio1!', 'wordpress'])
	mas.append(['wix', 'wix', 'violin78@protonmail.com', 'Viovio1!', 'wix'])
	mas.append(['alp', 'alpaca', 'violin78@protonmail.com', 'viovioviovio'])
	mas.append(['violin78@protonmail.com', 'Viovioviovio', 'Viovioviovio1!'])
	mas.append(['ama', 'amazon', 'media788788@gmail.com', 'Medmed1!', 'amazon'])
	mas.append(['ama', 'amazon order', 'violin78@protonmail.com', 'Viovio1!', 'amazon order'])
	mas.append(['ant1', 'anthem', 'violin78', 'Vivivi1!', 'anthem'])
	mas.append(['ant2', 'anthem', 'violin78', 'Medmed1!', 'anthem'])
	mas.append(['ant', 'ant - medic', 'medicaid67', 'Medmed1!', 'ant - medic'])
	mas.append(['atl1', 'atl - card', '4435470506506030', 'Mikael', 'atl - card', '4435470506506030'])
	mas.append(['atl2', 'atlantic union', 'mikaels', 'Vvbd63Vvbd63!', 'atlantic union'])
	mas.append(['atl3', 'atlantic union', 'atlatl', 'Medmed1!', 'atlantic union', 'media788788@gmail.com'])
	mas.append(['cra1', 'craigslist computer', 'craigslist computer'])
	mas.append(['cra2', 'craigslist fbg', 'violin78@protonmail.com', 'Viovio1!', 'craigslist fbg'])
	mas.append(['cra3', 'craigslist login', 'violin78@protonmail.com', 'Viovio1!', 'craigslist login', 'Mikael'])
	mas.append(['dat', 'data.nasdaq', 'cello34@protonmail.colm', 'Celcelcelcel1!', 'token', 'xmefpKkxybsUgCpGhtqX'])
	mas.append(['dmv', 'dmv', '212331006', 'Vvbd63Vvbd63#', 'dmv', 'Sandstedt'])
	mas.append(['eba', 'ebay', 'media788788@gmail.com', 'Medmed1!', 'ebay'])
	mas.append(['fac', 'facebook', 'violin78@protonmail.com', 'Viovio1!', 'facebook', 'Haynesville'])
	mas.append(['fed', 'fedex', 'violin78', 'Viovio1!', 'fedex', 'Virginia'])
	mas.append(['get', 'gettr', 'violin789', 'viovio', 'gettr', '22472'])
	mas.append(['goo1', 'google drive', 'media475634@gmail.com', 'Medmed1!', 'google drive'])
	mas.append(['goo2', 'google drive', 'media788788@gmail.com', 'Medmed1!', 'google drive'])
	mas.append(['goo3', 'google drive', 'desk544', 'Desdes1!', 'google drive'])
	mas.append(['har', 'hardees', 'violin78@protonmail.com', 'Viovio1!', 'hardees'])
	mas.append(['hea', 'healow', 'media788788@gmail.com', 'Medmed1!', 'healow'])
	mas.append(['hom', 'home depot', 'media788788@gmail.com', 'Medmedmed1!', 'healow'])
	mas.append(['iex', 'iex', 'violin78@protonmail.com', 'Viovio1!', 'iex'])
	mas.append(['ins1', 'instacart', 'violin78@protonmail.com', 'Viovio1!', 'instacart'])
	mas.append(['ins2', 'instagram', 'media788788@gmail.com', 'Medmed1!', 'instagram'])
	mas.append(['lab', 'labcorp', 'violin78@protonmail.com', 'Viovio1!', 'labcorp'])
	mas.append(['lin', 'linkedin', 'violin78@protonmail.com', 'Viovio1!', 'linkedin'])
	mas.append(['low', 'lowes', 'violin78@protonmail.com', 'Viovio1!', 'lowes'])
	mas.append(['mwh', 'mwh', 'mwhos', 'mwhos123', 'mwh'])
	mas.append(['pay', 'paypal', 'gocubs7@protonmail.com', 'Vvbd63Vvbd63', 'paypal.com', 'paypal', 'Viovio1!'])
	mas.append(['pol', 'polygonscan', 'violin78', 'Viovio1!', 'polygonscan'])
	mas.append(['pro1', 'protonmail', 'cello34', 'celcel', 'protonmail'])
	mas.append(['pro2', 'protonmail', 'gocubs7', 'cubwsw', 'protonmail'])
	mas.append(['pro3', 'protonmail', 'nova56', 'novnov', 'protonmail'])
	mas.append(['pro4', 'protonmail', 'violin78', 'viovio', 'protonmail'])
	mas.append(['que', 'quest', 'violin78@protonmail.com', 'Viovio1!', 'quest'])
	mas.append(['quo', 'quora', 'table65@mail.com', 'Tabtab1!', 'quora'])
	mas.append(['red', 'reddit', 'pizza_4_all_', 'cheesepizza', 'reddit'])
	mas.append(['rum', 'rumble', 'violin78@protonmail.com', 'Viovio1!', 'rumble'])
	mas.append(['sky1', 'skype - my account', 'violin78@mail.com', 'vioviovio1', 'skype - my account'])
	mas.append(['sky2', 'skype - web', 'violin78@mail.com', 'vioviovio1', 'skype - web'])
	mas.append(['swe1', 'swe-mas', 'Mikael Sandstedt', '5168 1531 3323 9073,04-24,818', 'swe-mas'])
	mas.append(['swe2', 'swedbank', '199007305411', '70197019', 'swedbank'])
	mas.append(['tar', 'target', 'violin78@protonmail.com', 'Viovio1!', 'target'])
	mas.append(['twi', 'twitter', 'media788788@gmail.com', 'Medmed1!', 'twitter', 'violin8374'])
	mas.append(['unh1', 'unhcr,1', '1,violin78@protonmail.com', '199007305411', 'unhcr,1'])
	mas.append(['unh2', 'unhcr', '1', 'violin78@protonmail.com', '199007305411', 'unhcr', '731431617'])
	mas.append(['ups1', 'ups', 'media788788@gmail.com', 'Medmedmedmed1!', 'ups'])
	mas.append(['ups2', 'ups', 'violin78@protonmail.com', 'Medmedmedmed1!', 'ups'])
	mas.append(['vhc', 'vhc', 'cello34', 'Celcel1!', 'vhc'])
	mas.append(['wal', 'walmart', 'violin78@protonmail.com', 'Viovio1!', 'walmart'])
	mas.append(['wix', 'wix', 'violin78@protonmail.com', 'Viovio1!', 'wix'])
	mas.append(['wor', 'wordpress', 'violin78@protonmail.com', 'Viovio1!', 'wordpress'])

	return mas
inp = []
log(inp)